#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
if (file_exists($publicPath = __DIR__.'/vendor/autoload.php')) {
    require $publicPath;
} elseif (file_exists($publicPath = __DIR__.'/../vendor/autoload.php')) {
    require $publicPath;
} else {
    require __DIR__.'/vendor/autoload.php';
}

// Bootstrap Laravel and handle the command...
$status = require_once __DIR__.'/bootstrap/app.php';

$status->handleCommand(
    new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);
