import 'package:flutter/material.dart';
import '../services/api_service.dart';
import 'admin_dashboard.dart';

class AdminOversightScreen extends StatefulWidget { const AdminOversightScreen({super.key}); @override State<AdminOversightScreen> createState()=>_AdminOversightScreenState(); }
class _AdminOversightScreenState extends State<AdminOversightScreen>{
 bool loading=true; Map<String,dynamic>? data;
 @override void initState(){super.initState();_load();}
 Future<void> _load() async {setState(()=>loading=true);final d=await ApiService.adminOverview();if(mounted)setState((){data=d;loading=false;});}
 Future<void> _registerVendor() async {final form=GlobalKey<FormState>();final name=TextEditingController(),user=TextEditingController(),pin=TextEditingController(),info=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Register Vendor'),content:Form(key:form,child:SingleChildScrollView(child:Column(children:[TextFormField(controller:name,decoration:const InputDecoration(labelText:'Vendor / business name'),validator:(v)=>v!.trim().isEmpty?'Required':null),TextFormField(controller:user,decoration:const InputDecoration(labelText:'Default username'),validator:(v)=>v!.trim().isEmpty?'Required':null),TextFormField(controller:pin,obscureText:true,decoration:const InputDecoration(labelText:'Default PIN'),validator:(v)=>v!.length<4?'Minimum 4 characters':null),TextFormField(controller:info,decoration:const InputDecoration(labelText:'Business information'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),ElevatedButton(onPressed:()=>form.currentState!.validate()?Navigator.pop(context,true):null,child:const Text('Create Vendor'))]));if(ok==true){final r=await ApiService.adminCreateVendor(fullName:name.text,username:user.text,pin:pin.text,info:info.text);if(mounted){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(r!=null?'Vendor registered. Credentials created securely.':'Vendor registration failed.')));_load();}}}
 @override Widget build(BuildContext context){final s=Map<String,dynamic>.from(data?['statistics']??{});final vendors=List<dynamic>.from(data?['vendor_summary']??[]);final workers=List<dynamic>.from(data?['workers']??[]);final shifts=List<dynamic>.from(data?['shifts_today']??[]);final activity=List<dynamic>.from(data?['recent_activity']??[]);return Scaffold(appBar:AppBar(title:const Text('Admin System Oversight'),actions:[IconButton(onPressed:_registerVendor,icon:const Icon(Icons.person_add)),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AdminDashboardScreen())),icon:const Icon(Icons.dashboard)),IconButton(onPressed:_load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(12),children:[GridView.count(crossAxisCount:2,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),childAspectRatio:2.2,children:[_stat('Vendors','${s['vendors']??0}'),_stat('Workers','${s['workers']??0}'),_stat('Orders','${s['orders']??0}'),_stat('Revenue','GH₵ ${((s['revenue']??0) as num).toStringAsFixed(2)}'),_stat('Today','GH₵ ${((s['revenue_today']??0) as num).toStringAsFixed(2)}'),_stat('Shifts Today','${s['shifts_today']??0}')]),const SizedBox(height:16),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('VENDOR PERFORMANCE',style:TextStyle(fontWeight:FontWeight.bold)),TextButton.icon(onPressed:_registerVendor,icon:const Icon(Icons.add),label:const Text('Register Vendor'))]),...vendors.map((v)=>Card(child:ListTile(title:Text(v['fullName']??''),subtitle:Text('${v['workers']} workers • ${v['orders']} orders • ${v['completed_orders']} completed'),trailing:Text('GH₵ ${((v['revenue']??0) as num).toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold)))),const SizedBox(height:16),const Text('TODAY\'S SHIFTS',style:TextStyle(fontWeight:FontWeight.bold)),if(shifts.isEmpty)const ListTile(title:Text('No shifts scheduled today.')),...shifts.map((x)=>ListTile(leading:const Icon(Icons.schedule),title:Text(x['worker']?['full_name']??'Worker'),subtitle:Text('${x['start_time']} – ${x['end_time']} • ${x['vendor']?['fullName']??''}'))),const SizedBox(height:16),const Text('WORKFORCE',style:TextStyle(fontWeight:FontWeight.bold)),...workers.take(30).map((w)=>ListTile(leading:const Icon(Icons.badge),title:Text(w['full_name']??''),subtitle:Text('${w['position']??'Staff'} • ${w['vendor']?['fullName']??''}'))),const SizedBox(height:16),const Text('RECENT SYSTEM ACTIVITY',style:TextStyle(fontWeight:FontWeight.bold)),...activity.take(30).map((a)=>ListTile(dense:true,leading:const Icon(Icons.security,size:18),title:Text(a['action']??''),subtitle:Text(a['details']??'')))])));}
 Widget _stat(String a,String b)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(b,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(a,style:const TextStyle(fontSize:11))])));
}
