import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/auth_provider.dart';
import 'student_dashboard_screen.dart';
import 'vendor_dashboard_screen.dart';
import 'admin_oversight_screen.dart';

class LoginScreen extends StatefulWidget { const LoginScreen({Key? key}) : super(key: key); @override State<LoginScreen> createState()=>_LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen>{
 final _usernameController=TextEditingController(); final _passwordController=TextEditingController(); String _selectedRole='STUDENT';
 void _login() async {final auth=Provider.of<AuthProvider>(context,listen:false);final username=_usernameController.text.trim().isNotEmpty?_usernameController.text.trim():_selectedRole.toLowerCase();final success=await auth.login(username,_passwordController.text);if(!mounted)return;if(success&&auth.currentUser!=null){switch(auth.currentUser!.role.toUpperCase()){case 'ADMIN':Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const AdminOversightScreen()));break;case 'VENDOR':Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const VendorDashboardScreen()));break;default:Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const StudentDashboardScreen()));}}else{ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(auth.errorMessage??'Login failed. Please check credentials.')));}}
 @override Widget build(BuildContext context){final auth=Provider.of<AuthProvider>(context);return Scaffold(body:Container(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.orange.shade800,Colors.deepOrange.shade900])),child:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.symmetric(horizontal:24),child:Card(shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),elevation:8,child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.restaurant_menu,size:64,color:Colors.deepOrange),const SizedBox(height:12),const Text('ATU Cafeteria',style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const Text('Smart Campus Food Ordering',style:TextStyle(color:Colors.grey,fontSize:14)),const SizedBox(height:24),Row(mainAxisAlignment:MainAxisAlignment.center,children:['STUDENT','VENDOR','ADMIN'].map((role){final selected=_selectedRole==role;return Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:ChoiceChip(label:Text(role),selected:selected,onSelected:(_){setState((){_selectedRole=role;_usernameController.text=role.toLowerCase();});}));}).toList()),const SizedBox(height:16),TextField(controller:_usernameController,decoration:InputDecoration(labelText:'Username / Student ID',prefixIcon:const Icon(Icons.person),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))),const SizedBox(height:16),TextField(controller:_passwordController,obscureText:true,decoration:InputDecoration(labelText:'Password / PIN',prefixIcon:const Icon(Icons.lock),border:OutlineInputBorder(borderRadius:BorderRadius.circular(12)))),const SizedBox(height:24),SizedBox(width:double.infinity,height:50,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Colors.deepOrange,foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(12))),onPressed:auth.isLoading?null:_login,child:auth.isLoading?const CircularProgressIndicator(color:Colors.white):const Text('Sign In',style:TextStyle(fontSize:16,fontWeight:FontWeight.bold)))),const SizedBox(height:12),TextButton(onPressed:(){_usernameController.text='student';_passwordController.text='1234';_login();},child:const Text('Quick Student Demo Login'))])))))));}
}
