name: atu_cafeteria
description: A modern, secure mobile food portal & vendor performance analytics system for Accra Technical University.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  google_generative_ai: ^0.2.0 # Incorporating real Gemini AI capabilities!
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
