import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../providers/admin_state_provider.dart';
import '../providers/cafeteria_provider.dart';
import '../widgets/reference_design.dart';

class ReferenceAdminScreen extends StatefulWidget{const ReferenceAdminScreen({super.key});@override State<ReferenceAdminScreen> createState()=>_ReferenceAdminScreenState();}
class _ReferenceAdminScreenState extends State<ReferenceAdminScreen>{String page='Dashboard';
@override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_){final c=context.read<CafeteriaProvider>();final a=context.read<AdminStateProvider>();a.setToken(c.authToken);a.loadAll();});}
@override Widget build(BuildContext context){final c=context.watch<CafeteriaProvider>();final a=context.watch<AdminStateProvider>();return Scaffold(body:SafeArea(child:LayoutBuilder(builder:(context,b){if(b.maxWidth<900)return _mobile(c,a);return Row(children:[Sidebar(selected:page,onSelected:(v)=>setState(()=>page=v),onLogout:(){c.logOut();Navigator.pushReplacementNamed(context,'/login');}),Expanded(child:_body(a))]);})));}
Widget _mobile(CafeteriaProvider c,AdminStateProvider a)=>Column(children:[Container(height:64,color:AppTheme.primary,padding:const EdgeInsets.symmetric(horizontal:16),child:Row(children:[AtuBrand.title(compact:true),const Spacer(),IconButton(onPressed:a.loadAll,icon:const Icon(Icons.refresh,color:Colors.white)),IconButton(onPressed:(){c.logOut();Navigator.pushReplacementNamed(context,'/login');},icon:const Icon(Icons.logout,color:Colors.white))])),Expanded(child:_body(a)),NavigationBar(selectedIndex:['Dashboard','Users','Vendors','Orders'].indexOf(page).clamp(0,3),onDestinationSelected:(i)=>setState(()=>page=['Dashboard','Users','Vendors','Orders'][i]),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.people),label:'Users'),NavigationDestination(icon:Icon(Icons.store),label:'Vendors'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Orders')])]);
Widget _body(AdminStateProvider a){if(page=='Dashboard')return _dashboard(a);final List<Map<String,dynamic>> rows=page=='Users'?a.users:page=='Vendors'?a.vendors:a.orders;return ListView(padding:const EdgeInsets.all(24),children:[Text('All $page',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const SizedBox(height:14),ReferenceCard(child:Column(children:rows.isEmpty?[const Padding(padding:EdgeInsets.all(24),child:Text('No records available.'))]:rows.take(20).map((r)=>ListTile(title:Text('${r['fullName']??r['full_name']??r['name']??r['id']??'Record'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${r['username']??r['email']??r['status']??r['role']??''}'),trailing:const Icon(Icons.chevron_right)).toList()))]);}
Widget _dashboard(AdminStateProvider a){final d=a.dashboardData;return ListView(padding:const EdgeInsets.all(24),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:AppTheme.primary,borderRadius:BorderRadius.circular(20)),child:const Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Welcome, Admin!',style:TextStyle(color:Colors.white,fontSize:24,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Here’s an overview of your cafeteria system.',style:TextStyle(color:Colors.white70))])),Icon(Icons.admin_panel_settings,color:AppTheme.accent,size:50)])),const SizedBox(height:18),Wrap(spacing:12,runSpacing:12,children:[MetricTile(label:'Total Users',value:'${d['users']??d['total_users']??0}',icon:Icons.people),MetricTile(label:'Total Vendors',value:'${d['vendors']??d['total_vendors']??0}',icon:Icons.store),MetricTile(label:'Total Orders',value:'${d['orders']??d['total_orders']??0}',icon:Icons.receipt_long),const MetricTile(label:'Average Rating',value:'4.3 ★',icon:Icons.star)]),const SizedBox(height:20),ReferenceCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Vendor Performance Overview',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const SizedBox(height:15),_bar('Emanuella Adu Dudaa',92),_bar('Lovelace Lartey Adams',78),_bar('KV Bakery',64),_bar('Joll of Rice & Chicken',58),_bar('Donut (Chocolate)',46)]))]);}
Widget _bar(String label,int value)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(children:[SizedBox(width:170,child:Text(label,style:const TextStyle(fontSize:11))),Expanded(child:LinearProgressIndicator(value:value/100,minHeight:12,backgroundColor:AppTheme.border,valueColor:const AlwaysStoppedAnimation(AppTheme.primary))),const SizedBox(width:8),Text('$value',style:const TextStyle(fontWeight:FontWeight.w900))]));
}