import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/theme/app_theme.dart';
import '../../domain/models/models.dart';
import '../providers/cafeteria_provider.dart';
import '../widgets/reference_design.dart';

class ReferenceVendorScreen extends StatefulWidget {
  const ReferenceVendorScreen({super.key});
  @override State<ReferenceVendorScreen> createState() => _ReferenceVendorScreenState();
}

class _ReferenceVendorScreenState extends State<ReferenceVendorScreen> {
  String page = 'Dashboard';
  @override Widget build(BuildContext context) {
    final p = context.watch<CafeteriaProvider>();
    return Scaffold(body: SafeArea(child: LayoutBuilder(builder: (context, c) {
      final wide = c.maxWidth >= 900;
      if (!wide) return Column(children: [
        Container(height: 64,color: AppTheme.primary,padding: const EdgeInsets.symmetric(horizontal: 16),child: Row(children:[AtuBrand.title(compact:true),const Spacer(),IconButton(onPressed:p.refreshAllData,icon:const Icon(Icons.refresh,color:Colors.white)),IconButton(onPressed:(){p.logOut();Navigator.pushReplacementNamed(context,'/login');},icon:const Icon(Icons.logout,color:Colors.white))])),
        Expanded(child:_content(p)),
        NavigationBar(selectedIndex:_index,onDestinationSelected:(i)=>setState(()=>page=['Dashboard','Menu Catalog','Orders','Performance'][i]),destinations:const [NavigationDestination(icon:Icon(Icons.dashboard),label:'Dashboard'),NavigationDestination(icon:Icon(Icons.restaurant_menu),label:'Menu'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Orders'),NavigationDestination(icon:Icon(Icons.insights),label:'Performance')])
      ]);
      return Row(children:[Sidebar(selected:page,onSelected:(v)=>setState(()=>page=v),onLogout:(){p.logOut();Navigator.pushReplacementNamed(context,'/login');},vendor:true),Expanded(child:Column(children:[Container(height:68,padding:const EdgeInsets.symmetric(horizontal:24),decoration:const BoxDecoration(color:Colors.white,border:Border(bottom:BorderSide(color:AppTheme.border))),child:Row(children:[Expanded(child:Text(page,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900,color:AppTheme.textDark))),StatusPill(p.currentUser?.isOpen==true?'Open':'Closed'),const SizedBox(width:12),IconButton(onPressed:p.refreshAllData,icon:const Icon(Icons.refresh))])),Expanded(child:_content(p))]))]);
    })));
  }
  int get _index => ['Dashboard','Menu Catalog','Orders','Performance'].indexOf(page).clamp(0,3);
  Widget _content(CafeteriaProvider p){switch(page){case 'Menu Catalog':return _menu(p);case 'Orders':return _orders(p);case 'Performance':return _performance(p);default:return _dashboard(p);}}
  Widget _dashboard(CafeteriaProvider p){final o=p.vendorOrders;final active=o.where((x)=>!['COMPLETED','DELIVERED','CANCELLED','DECLINED'].contains(x.status.toUpperCase())).length;return ListView(padding:const EdgeInsets.all(24),children:[const Text('Vendor Performance',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const Text('Manage your campus store and customer orders.'),const SizedBox(height:18),Wrap(spacing:12,runSpacing:12,children:[MetricTile(label:'Total Orders',value:'${o.length}',icon:Icons.receipt_long),MetricTile(label:'Active Orders',value:'$active',icon:Icons.timelapse),const MetricTile(label:'Rating',value:'4.7 ★',icon:Icons.star),MetricTile(label:'Menu Items',value:'${p.vendorFoodItems.length}',icon:Icons.restaurant_menu)]),const SizedBox(height:20),ReferenceCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Recent Orders',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const SizedBox(height:12),...o.take(5).map(_row)]))]);}
  Widget _menu(CafeteriaProvider p)=>ListView(padding:const EdgeInsets.all(24),children:[Row(children:[const Expanded(child:Text('Menu Catalog',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.textDark))),FilledButton.icon(onPressed:()=>_addFood(p),icon:const Icon(Icons.add),label:const Text('Add Food'))]),const SizedBox(height:14),...p.vendorFoodItems.map((f)=>Padding(padding:const EdgeInsets.only(bottom:10),child:ReferenceCard(child:Row(children:[FoodImage(url:f.imageUrl),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(f.name,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w900,color:AppTheme.textDark)),Text(f.category,style:const TextStyle(color:AppTheme.textMuted)),const SizedBox(height:4),Text('GH₵ ${f.price.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.w900,color:AppTheme.primary))])),StatusPill(f.isAvailable?'Available':'Unavailable')]))))]);
  Widget _orders(CafeteriaProvider p)=>ListView(padding:const EdgeInsets.all(24),children:[const Text('Orders',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const SizedBox(height:14),ReferenceCard(child:Column(children:p.vendorOrders.isEmpty?[const Padding(padding:EdgeInsets.all(20),child:Text('No customer orders yet.'))]:p.vendorOrders.map(_row).toList()))]);
  Widget _row(Order o)=>Padding(padding:const EdgeInsets.symmetric(vertical:9),child:Row(children:[SizedBox(width:90,child:Text('#ATU-${o.id??0}',style:const TextStyle(fontWeight:FontWeight.w900))),Expanded(child:Text('${o.foodName} × ${o.quantity}')),Text('GH₵ ${o.totalPrice.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(width:10),StatusPill(o.displayStatus),const SizedBox(width:8),_next(o)]));
  Widget _next(Order o){final s=o.status.toUpperCase();String? n;if(s=='PENDING'||s=='ORDER_PLACED')n='PREPARING';else if(s=='PREPARING')n='READY';else if(s=='READY'||s=='READY_FOR_PICKUP')n='COMPLETED';if(n==null||o.id==null)return const SizedBox(width:88);return SizedBox(width:105,child:FilledButton(onPressed:()async{await context.read<CafeteriaProvider>().updateOrderStatus(o.id!,n!);if(mounted)setState((){});},child:Text(n=='COMPLETED'?'Verify Pickup':'Mark ${n=='READY'?'Ready':'Preparing'}',style:const TextStyle(fontSize:9))));}
  Widget _performance(CafeteriaProvider p){final revenue=p.vendorOrders.fold<double>(0,(a,o)=>a+o.totalPrice);return ListView(padding:const EdgeInsets.all(24),children:[const Text('Performance',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900,color:AppTheme.textDark)),const SizedBox(height:14),Wrap(spacing:12,runSpacing:12,children:[MetricTile(label:'Revenue',value:'GH₵ ${revenue.toStringAsFixed(2)}',icon:Icons.payments),MetricTile(label:'Completed',value:'${p.vendorOrders.where((o)=>o.status.toUpperCase()=='COMPLETED').length}',icon:Icons.check_circle),const MetricTile(label:'Prep Speed',value:'12.5 min',icon:Icons.timer),const MetricTile(label:'Rating',value:'4.7 ★',icon:Icons.star)]),const SizedBox(height:20),const ReferenceCard(child:Center(child:Padding(padding:EdgeInsets.all(35),child:Icon(Icons.show_chart,size:80,color:AppTheme.primary))))]);}
  Future<void> _addFood(CafeteriaProvider p)async{final n=TextEditingController(),pr=TextEditingController(),d=TextEditingController();String cat='Lunch Specials';final ok=await showDialog<bool>(context:context,builder:(context)=>StatefulBuilder(builder:(context,setD)=>AlertDialog(title:const Text('Add Food Item'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Food name')),const SizedBox(height:10),TextField(controller:pr,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Price (GH₵)')),const SizedBox(height:10),DropdownButtonFormField<String>(value:cat,items:const ['Lunch Specials','Traditional','Drinks','Snacks'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setD(()=>cat=v??cat),decoration:const InputDecoration(labelText:'Category')),const SizedBox(height:10),TextField(controller:d,maxLines:2,decoration:const InputDecoration(labelText:'Description'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()async{final value=double.tryParse(pr.text);if(n.text.trim().isEmpty||value==null||value<=0)return;final result=await p.addVendorFoodItem(n.text,value,cat,d.text);if(context.mounted)Navigator.pop(context,result);},child:const Text('Add Food'))]));n.dispose();pr.dispose();d.dispose();if(ok==true&&mounted){await p.refreshAllData();setState((){});ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Food item added successfully.')));}}
}
